/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AButtonGroup: (typeof import('ant-design-vue/es'))['ButtonGroup']
    ACard: (typeof import('ant-design-vue/es'))['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADivider: (typeof import('ant-design-vue/es'))['Divider']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ArrowOutlined: typeof import('@ant-design/icons-vue')['ArrowOutlined']
    CaretRightOutlined: typeof import('@ant-design/icons-vue')['CaretRightOutlined']
    Contextmenu: typeof import('./src/components/contextmenu/Contextmenu.vue')['default']
    DraggableGroup: typeof import('./src/components/drag/DraggableGroup.vue')['default']
    DraggableHistory: typeof import('./src/components/drag/history/DraggableHistory.vue')['default']
    DraggableTree: typeof import('./src/components/drag/DraggableTree.vue')['default']
    DraggableTreeGroup: (typeof import('./src/components/drag/DraggableTreeGroup.vue'))['default']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    LeftOutlined: typeof import('@ant-design/icons-vue')['LeftOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tree: (typeof import('./src/components/drag/Tree.vue'))['default']
    TreeGroup: (typeof import('./src/components/drag/TreeGroup.vue'))['default']
  }
}
