/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: (typeof import('ant-design-vue/es'))['Checkbox']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInputNumber: (typeof import('ant-design-vue/es'))['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ATable: (typeof import('ant-design-vue/es'))['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: (typeof import('ant-design-vue/es'))['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CaretRightOutlined: typeof import('@ant-design/icons-vue')['CaretRightOutlined']
    Contextmenu: typeof import('./src/components/contextmenu/Contextmenu.vue')['default']
    DraggableContainer: typeof import('./src/components/drag/DraggableContainer.vue')['default']
    DraggableHistory: typeof import('./src/components/drag/history/DraggableHistory.vue')['default']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    History: typeof import('./src/components/history/History.vue')['default']
    PrimaryContextmenu: (typeof import('./src/components/contextmenu/PrimaryContextmenu.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubContextmenu: typeof import('./src/components/contextmenu/SubContextmenu.vue')['default']
    Tree: typeof import('./src/components/tree/Tree.vue')['default']
  }
}
