/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    CaretRightOutlined: typeof import('@ant-design/icons-vue')['CaretRightOutlined']
    Contextmenu: typeof import('./src/components/contextmenu/Contextmenu.vue')['default']
    DraggableContainer: typeof import('./src/components/drag/DraggableContainer.vue')['default']
    DraggableGroup: typeof import('./src/components/drag/DraggableGroup.vue')['default']
    DraggableHistory: typeof import('./src/components/drag/history/DraggableHistory.vue')['default']
    DraggableTree: typeof import('./src/components/drag/DraggableTree.vue')['default']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    History: typeof import('./src/components/history/History.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubContextmenu: typeof import('./src/components/contextmenu/SubContextmenu.vue')['default']
    Tree: typeof import('./src/components/tree/Tree.vue')['default']
  }
}
